# Generated by Django 3.2.6 on 2022-05-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tba',
            table=None,
        ),
    ]
