# Generated by Django 3.2.6 on 2022-05-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tba_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tba',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tba',
            name='updated_at',
        ),
    ]
